In [1]:
import torch
import numpy as np

### 4.1.1 數值類型

In [2]:
a = 1.2
aa = torch.tensor(1.2)
type(a), torch.is_tensor(a), type(aa), torch.is_tensor(aa)

(float, False, torch.Tensor, True)

In [3]:
x = torch.tensor([1.2, 3.3])
x

tensor([1.2000, 3.3000])

In [4]:
x.numpy()

array([1.2, 3.3], dtype=float32)

In [5]:
a = torch.tensor([1.2])
a, a.shape, a.dtype

(tensor([1.2000]), torch.Size([1]), torch.float32)

In [6]:
a = torch.tensor([1.2, 3.])
a, a.shape, a.dtype

(tensor([1.2000, 3.0000]), torch.Size([2]), torch.float32)

In [7]:
a = torch.tensor([[1, 2], [3, 4]])
a, a.shape, a.dtype

(tensor([[1, 2],
         [3, 4]]),
 torch.Size([2, 2]),
 torch.int64)

In [8]:
a = torch.tensor([[[1, 2], [3, 4], [5, 6], [7, 8]]])
a, a.shape, a.dtype

(tensor([[[1, 2],
          [3, 4],
          [5, 6],
          [7, 8]]]),
 torch.Size([1, 4, 2]),
 torch.int64)

### 4.1.2 字符串類型

不支援

### 4.1.3 布爾類型

In [9]:
a = torch.tensor(True)
a, a.dtype

(tensor(True), torch.bool)

In [10]:
a = torch.tensor([True, False])
a, a.dtype

(tensor([ True, False]), torch.bool)

In [11]:
a = torch.tensor(True)
a is True, a == True

(False, tensor(True))

### 4.2 數值精度

In [12]:
torch.set_printoptions(precision=30)

In [13]:
torch.tensor(123456789, dtype=torch.int16), torch.tensor(123456789, dtype=torch.int32)

(tensor(-13035, dtype=torch.int16), tensor(123456789, dtype=torch.int32))

In [14]:
torch.tensor(np.pi, dtype=torch.float32), torch.tensor(np.pi, dtype=torch.float64)

(tensor(3.141592741012573242187500000000),
 tensor(3.141592653589793115997963468544, dtype=torch.float64))

### 4.2.1 讀取精度

In [15]:
a = torch.tensor(np.pi, dtype=torch.float16)
print('before:', a.dtype)

if a.dtype!=torch.float32:
    a = a.type(torch.float32)
print('after :', a.dtype)

before: torch.float16
after : torch.float32


### 4.2.2 類型轉換

In [16]:
a = torch.tensor(np.pi, dtype=torch.float16)
a.double()

tensor(3.140625000000000000000000000000, dtype=torch.float64)

In [17]:
a = torch.tensor(123456789, dtype=torch.int32)
a.type(torch.int16)

tensor(-13035, dtype=torch.int16)

In [18]:
a = torch.tensor([True, False])
a.type(torch.int32)

tensor([1, 0], dtype=torch.int32)

In [19]:
a = torch.tensor([-1, 0, 1, 2])
a.bool()

tensor([ True, False,  True,  True])

### 4.3 待優化張量

pytorch已經將Tensor和Variable合併了

### 4.4.1 從數組、列表對象創建

In [20]:
a = [1, 2.]
aa = torch.tensor(a)
a, type(a), aa, type(aa)

([1, 2.0], list, tensor([1., 2.]), torch.Tensor)

In [21]:
a = np.array([[1, 2.], [3, 4]])
aa = torch.tensor(a)
a, type(a), aa, type(aa)

(array([[1., 2.],
        [3., 4.]]),
 numpy.ndarray,
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float64),
 torch.Tensor)

### 4.4.2 創建全0或全1張量

In [22]:
torch.zeros([]), torch.ones([])

(tensor(0.), tensor(1.))

In [23]:
torch.zeros([1]), torch.ones([1])

(tensor([0.]), tensor([1.]))

In [24]:
torch.zeros([2, 2]), torch.ones([3, 2])

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [25]:
a = torch.ones([2, 3])
torch.zeros_like(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
a = torch.zeros([3, 2])
torch.ones_like(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### 4.4.3 創建自定義張量數值

In [27]:
torch.full([], -1)

tensor(-1)

In [28]:
torch.full([1], -1)

tensor([-1])

In [29]:
torch.full([2, 2], 99)

tensor([[99, 99],
        [99, 99]])

### 4.4.4 創建已知分布的張量

In [30]:
torch.randn([2, 2])

tensor([[ 0.640894472599029541015625000000, -0.275541335344314575195312500000],
        [-0.302168846130371093750000000000,  1.025027394294738769531250000000]])

In [31]:
torch.zeros([2,3]).normal_(1, 2)

tensor([[-1.935149788856506347656250000000,  0.908433020114898681640625000000,
          1.280202269554138183593750000000],
        [-3.771430492401123046875000000000,  2.295819759368896484375000000000,
          1.645455837249755859375000000000]])

In [32]:
torch.rand([2, 2])

tensor([[0.392899632453918457031250000000, 0.599044799804687500000000000000],
        [0.592756927013397216796875000000, 0.537213265895843505859375000000]])

In [33]:
torch.zeros([2,3]).uniform_(0, 10)

tensor([[4.990239620208740234375000000000, 0.376384854316711425781250000000,
         5.574605941772460937500000000000],
        [5.458689212799072265625000000000, 0.129725933074951171875000000000,
         5.918767452239990234375000000000]])

In [34]:
torch.randint(low=0, high=100, size=[2, 2])

tensor([[32,  7],
        [21, 26]])

### 4.4.5 創建序列

In [35]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

沒辦法\
torch.arange(10, 2)

In [36]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

### 4.5.1 標量

In [37]:
import torch.nn.functional as F
from torch import nn
out = torch.rand([4, 10])
y = torch.tensor([2, 3, 2, 0])
y = F.one_hot(y, num_classes=10)
mse = nn.MSELoss()
loss = mse(y, out)
loss

tensor(0.327720195055007934570312500000)

### 4.5.2 張量

In [39]:
z = torch.randn([4, 2])
b = torch.zeros(2)
z = z + b
z

tensor([[-0.046799007803201675415039062500, -0.305063009262084960937500000000],
        [ 1.512414574623107910156250000000,  0.092237986624240875244140625000],
        [-0.295131504535675048828125000000,  0.261842936277389526367187500000],
        [-0.550323009490966796875000000000,  1.244505882263183593750000000000]])

In [ ]:
net = nn.Sequential()
net.add_module("linear1",nn.Linear(15,20))

### 4.5.3 矩陣

In [40]:
x = torch.randn([2, 4])
w = torch.ones([4, 3])
b = torch.zeros(3)
q = x@w + b
q

tensor([[-0.497186899185180664062500000000, -0.497186899185180664062500000000,
         -0.497186899185180664062500000000],
        [ 1.819610476493835449218750000000,  1.819610476493835449218750000000,
          1.819610476493835449218750000000]])